- CHANGELOG.md
- package.json
- src/writeFileToAssets.js
- tests/index.js
> Fix subdirectory errors in blob patterns

- README.md
> Add EMFILE and ENFILE error to FAQ

- README.md
> Add webpack-dev-server info to FAQ

- README.md
- src/preProcessPattern.js
- src/processPattern.js
- tests/index.js
> Changed default ignore glob to ignore dot files

- appveyor.yml
- src/preProcessPattern.js
- src/writeFile.js
- tests/index.js
Ensures we don't regress Windows support
> Added Appveyor for Windows testing

- package-lock.json
- src/writeFile.js
- tests/index.js
Also fix strange code when hash just check on true
- Fixes https://github.com/webpack-contrib/copy-webpack-plugin/issues/156
> fix: copy same file to multiple targets

- package-lock.json
- package.json
We don't use this deps anywhere in package
> chore(package): remove unused dependencies (`fs-extra`, `node-dir`)

- src/preProcessPattern.js
- src/writeFile.js
It just does not make sense to use a `var`
> refactor: use `const` instead `var`

- README.md
promote best practice in the docs
> docs(README): replace `var` with `const` in examples

- README.md
- tests/index.js
- https://github.com/webpack-contrib/copy-webpack-plugin/issues/93#issuecomment-291187698
- Fixes https://github.com/webpack-contrib/copy-webpack-plugin/issues/93
> test: nested directories in globs

- README.md
See https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/processPattern.js#L12
> docs(README): add `fromArg` option (`pattern.fromArgs`)

- .npmignore
- package.json
> chore(package): add `files` property to reduce package size

- src/index.js
Backwards compatible with Webpack 3 as well.
Closes #211
> fix(index): add `webpack >= v4.0.0` support

- src/preProcessPattern.js
- src/processPattern.js
- Fixes #226 
No tests, because we should catch this in window CI, but CI don't have this right now :disappointed:
> fix(src/): don't escape non-glob patterns

- package-lock.json
- package.json
- src/writeFile.js
- Some code was removed because he is fixed problems in old `loader-utils`.
- Use `absolute` path and `context` to right determinate interpolate name.
- Fixes #137
> chore(package): update `loader-utils` v0.2.15...1.1.0

- package-lock.json
- package.json
> fix(package): update `cacache` v10.0.1...10.0.4 (`dependencies`)

- README.md
> Update link to fileloader

- README.md
Fixed a total of 9 missing commas in the code examples.
#248 only fixes 3 of them.
> Fixed missing commas in code examples.

- README.md
- src/index.js
- test/CopyPlugin.test.js
Fix prototype
Yes, change `prototype` of plugin, now you can to get correct plugin name
fixes #315 fixes #314 fixes #268
> refactor: rewrite on class

- src/index.js
- src/postProcessPattern.js
- src/preProcessPattern.js
- src/processPattern.js
- test/CopyPlugin.test.js
Refactor, drop outdated code
No, after remove compatibility with webpack@3
No
> refactor: code

- src/index.js
- src/postProcessPattern.js
- src/preProcessPattern.js
- src/processPattern.js
Use `Set` instead `Array`
No
No
> refactor: migrate on Set

- src/preProcessPattern.js
- test/CopyPlugin.test.js
fixes #126
Yes
plugin emit warning instead error if file doesn't exist
No
> feat: emit warning instead error if file doesn't exist

- package-lock.json
- package.json
- src/preProcessPattern.js
- src/processPattern.js
- src/utils/normalize.js
- test/CopyPlugin.test.js
> fix: normalize path segment separation

- test/CopyPlugin.test.js
tests #266
No
Looks we already fixed this problem using `normalizePath` so i just add test to ensure all works as expected
> test: space in directory

- README.md
- package-lock.json
- package.json
- src/index.js
- src/postProcessPattern.js
- src/preProcessPattern.js
- src/processPattern.js
- test/CopyPlugin.test.js
Migrate on `webpack-log`
Yes, `debug` option was renamed to `logLevel`, it only accepts string values: `trace`, `debug`, `info`, `warn`, `error` and `silent`.
No
> refactor: debug option

- README.md
Update and fix docs about `logLevel` option
No
No
> docs: improve `logLevel` option description

- src/postProcessPattern.js
- src/preProcessPattern.js
Avoid extra call `stat` for file
No
No
> perf: avoid extra call `stat` for file

- src/utils/isTemplateLike.js
- test/CopyPlugin.test.js
fix bug
No
fixes #369 fixes #373
> fix: alone `[N]` interpolation in `to` option

- README.md
> docs: fix 'defined' typo in readme

- README.md
- src/index.js
- test/to-option.test.js
> docs: issue 408

- README.md
> docs: example for placeholders in `to`

- package-lock.json
- src/options.json
- test/validate-options.test.js
> fix: allow to setup empty array

- README.md
- package-lock.json
> chore(docs): fix typo

- README.md
As someone who copy-pastes examples before thoroughly reading the description I spent quite a while figuring out why my code doesn't work 😜
This PR fixes `from` pattern option example in the documentation
None
✌️
> Fix 'from' pattern option description

- test/CopyPlugin.test.js
Two test cases had been duplicated without changes.
None.
> Remove some duplicated tests

- README.md
- src/index.js
- src/options.json
- src/postProcessPattern.js
- test/CopyPlugin.test.js
fixes #360 and fixes #261
Yes
We should always have persist assets between rebuilds, the `force` option will be removed too
> Fix persist assets between rebuilds

- src/index.js
- src/preProcessPattern.js
- src/processPattern.js
> refactor: refactor

- README.md
- src/index.js
- src/options.json
- src/processPattern.js
- test/__snapshots__/validate-options.test.js.snap
- test/validate-options.test.js
Limits the number of simultaneous requests to fs
No
No
> feat: concurrency

- .github/workflows/nodejs.yml
- package.json
- src/postProcessPattern.js
- test/transform-option.test.js
> fix: asset size

- test/cacheTransform-option.test.js
- test/transform-option.test.js
add tests transform && transformPath
No
No
> chore: add tests transform && transformPath

- README.md
Edit readmy for `from` option
fixes #112 
fixes #456 
No
No
> chore: edit readmy for From option

- README.md
- src/options.json
- src/preProcessPattern.js
- src/processPattern.js
- src/utils/createPatternGlob.js
- test/__snapshots__/validate-options.test.js.snap
- test/globOptions-option.test.js
- test/noErrorOnMissing.test.js
- test/validate-options.test.js
implement new options `noErrorOnMissing` + improve schema
Yes, for schema
fixes #431 fixes #433
> feat: implement the `noErrorOnMissing` option

- src/index.js
- src/postProcessPattern.js
- src/preProcessPattern.js
- src/processPattern.js
- src/utils/createPatternGlob.js
- test/CopyPlugin.test.js
- test/__snapshots__/CopyPlugin.test.js.snap
- test/from-option.test.js
- test/globOptions-option.test.js
- test/toType-option.test.js
refactor code base
Yes, missing file is not an error
No
> Refactor code

- src/options.json
- src/postProcessPattern.js
- src/processPattern.js
- src/utils/createPatternGlob.js
- test/CopyPlugin.test.js
- test/__snapshots__/CopyPlugin.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/globOptions-option.test.js
- test/to-option.test.js
- test/validate-options.test.js
refactor code
No, because we don't respect cwd before
No
> Test coverage

- CHANGELOG.md
typo in logLevel in changelog file
N/A
N/A
> docs(changelog): fix logLevel typo

- src/index.js
- src/postProcessPattern.js
fixes #482
No
Hard to test so I added comment
> fix: concurrency writing assets

- package-lock.json
- package.json
> fix(security): update `serialize-javascript`

- test/CopyPlugin.test.js
- test/__snapshots__/CopyPlugin.test.js.snap
test for future cache between builds
No
Need refactor before start
> test: cache

- .github/workflows/nodejs.yml
- README.md
- package-lock.json
- package.json
- src/index.js
- test/CopyPlugin.test.js
- test/__snapshots__/CopyPlugin.test.js.snap
- test/helpers/enter-with-asset-modules.js
- test/helpers/getCompiler.js
fixes #538
No
- `sourceFilename` - the original filename relative to compilation context
> feat: added `sourceFilename` with original file to asset info

- README.md
- src/index.js
- src/options.json
- test/CopyPlugin.test.js
- test/__snapshots__/CopyPlugin.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/to-option.test.js
- test/validate-options.test.js
Added type `function` for `to` option
No
No
> feat: added type `function` for `to` option

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/validate-options.test.js.snap
- test/info-option.test.js
- test/validate-options.test.js
> Feat add info option

- src/index.js
fixes #568
No
Hard to test, because this api inside globby
> fix: compatibility with webpack 4 file system

- package-lock.json
- package.json
- test/globOptions-option.test.js
Fixed #496
No
Issue fixed in globby@11.0.2
> fix: issue 496

- README.md
Duplicates configuration snippet to `Examples` section in README as suggested in #576 
N/A
> docs(readme): add example to skip minimizing source files

- .github/workflows/nodejs.yml
- src/index.js
> ci: add Node.js 17

- package-lock.json
- package.json
- test/__snapshots__/validate-options.test.js.snap
> chore(deps): update

- .eslintignore
- .eslintrc.js
- .gitignore
- .prettierignore
- babel.config.js
- globalSetup.js
- jest.config.js
- package-lock.json
- package.json
- src/index.js
- test/CopyPlugin.test.js
- test/helpers/built-in-modules/fs.js
- test/helpers/built-in-modules/path.js
- test/helpers/built-in-modules/stream.js
- test/helpers/built-in-modules/util.js
update globby, new globby uses ESM, so we use `import()` to load it, for testing purposes we bundle globby using webpack to `commonjs` and use jest aliases to load bundled copy, unfortunately `import()` is broken in Jest, so without it we can't test our code
No
No
> chore(deps): update globby

- babel.config.js
- package.json
> chore(release): 10.0.0

- lint-staged.config.js
expand lint staged, use eslint cache
no
> fix: expand lint-staged

- .github/workflows/nodejs.yml
- src/index.js
- types/index.d.ts
> fix: types

- README.md
The signature given for options in the README did not include path strings (raised at #628).
> Add path string to options signature (fixes #628)

- .github/workflows/nodejs.yml
> chore: add node 18 to workflow

- package-lock.json
regenerate lock file and check tests
No
No
> chore(deps): regenerate lock file

- .github/CONTRIBUTING.md
> docs: fix typo errors

- package-lock.json
- package.json
update jest from v29 to v30
No
No
> chore: update jest from v29 to v30
