- index.js
- package.json
- test/index.js
Tried to avoid any breaking change for now.
In my opinion, it could be worth it to release a new breaking major after that only deals with globbing with both `cwd` and `base` options (like gulp/vinyl).
> feat(plugin): add globbing support for from option (fixes #7)

- index.js
- package.json
This adds support for lodash 4.0 which has breaking changes and replaces `_.contains` with `_.includes` per [Changelog](https://github.com/lodash/lodash/wiki/Changelog#jan-12-2016--diff--docs)
> Support lodash v4.0.0

- src/index.js
webpack version 1.12.12 + webpack-dev-server 1.14.1
Seems like `compiler.options.devServer` is **undefined** when user doesn't defined `devServer` in webpack config
it will throw `TypeError: Cannot read property 'outputPath' of undefined`  at function `getOutputDir()`
So the customized error won't be thrown out
> Fix TypeError when working with webpack-dev-server

- src/toLooksLikeDirectory.js
node 6.0.0 + webpack 1.12.12
to reproduce this error, simply provide a file path in `from ` and omit `to`
like this in webpack config
`plugins: [
new CopyWebpackPlugin([{ from: 'src/static/index.html' }]),
],`
> Fix ERROR in Path must be a string. Received undefined

- src/index.js
there was a breaking change in the recent patch. This change allows for destructuring 
https://github.com/AngularClass/angular2-webpack-starter/issues/585
`const CopyWebpackPlugin = require('copy-webpack-plugin').CopyWebpackPlugin`
`const {CopyWebpackPlugin} = require('copy-webpack-plugin')`
`const CopyWebpackPlugin = require('copy-webpack-plugin').default`
you can also support all imports via 
```typescript
function CopyWebpackPlugin () { /* ... */}
CopyWebpackPlugin['default'] = CopyWebpackPlugin;
// commonjs
export = CopyWebpackPlugin;
```
`const CopyWebpackPlugin = require('copy-webpack-plugin').CopyWebpackPlugin`
`const {CopyWebpackPlugin} = require('copy-webpack-plugin')`
`const CopyWebpackPlugin = require('copy-webpack-plugin').default`
`const CopyWebpackPlugin = …
> refactor(index): export as prop and default

- CHANGELOG.md
- README.md
- package.json
- src/index.js
- src/writeDirectoryToAssets.js
- src/writeFileToAssets.js
- tests/index.js
Remove dependence on special devServer config. Rely on [write-file-webpack-plugin](https://github.com/gajus/write-file-webpack-plugin) to write directly to filesystem when running devServer (if desired)
> Don't write to filesystem directly

- src/index.js
- src/preProcessPattern.js
- src/processPattern.js
- src/writeFile.js
- tests/index.js
This allows any name template that [file-loader accepts](https://github.com/webpack/file-loader). It also uses a map to process each file concurrently to improve performance when copying many files.
> Added name templates and improved performance

- src/processPattern.js
improved windows compatibility, in reference to #84
most tests now pass on windows. the code line added was taken from the original writeFileToAssets.js, line 14
> improved windows compatibility

- src/index.js
Before: *200ms* per rebuild (and an additional 200ms for each additional rebuild) 
After: *~5ms* per rebuild!
Hi! Thanks for the awesome plugin! It has saved my life on many projects. One of my coworkers today was experiencing slow rebuilds in watch mode, and with a little bit of profiling, it turns out this plugin was the culprit. There are 2 issues:
1. a memory leak that causes the fileDependencies and contextDependencies to grow after each save.
2. An `O(n)` `_.includes` call that can be replaced with an `O(1)` `Set.prototype.has` call.
Here are the performance characteristics of this patch. The project in question is private, but has 1800 files. The `did it` line is how long this plugin takes to complete:
```
did it: 386.245ms                                                     
Hash: …
```
> fix: Memory leak in watch mode and use Set for performance

- README.md
- src/preProcessPattern.js
- tests/index.js
> feat: support `{String}` patterns

- src/writeFile.js
- tests/index.js
Currently implemented a way of the transform is synchronous transform only available. Fixing little makes asynchronous transform available.
> feat: allow async transforms

- README.md
- src/index.js
- tests/index.js
Overrides webpack context, overridden by pattern context
Fixes #148
> feat: add `context` option (`options.context`)

- package-lock.json
- package.json
- src/index.js
- src/preProcessPattern.js
- src/processPattern.js
- src/writeFile.js
- tests/index.js
Node which we support have native implementation `Promise`.
> refactor: use native `{Promise}` instead of `bluebird`

- .eslintrc.json
- README.md
- package-lock.json
- package.json
- src/index.js
- src/writeFile.js
- tests/index.js
> feat: add option to cache `pattern.transform` (`pattern.cache`)

- src/writeFile.js
- `fs.readFile` return `{String|Buffer}`, JSON doesn't make sense here. Just `toString()` and save in cache
> refactor(writeFile): use `data.toString()` instead of `JSON.stringify()` to serialize the `cache` data (`patterns.cache`) 

- package.json
- src/index.js
- src/preProcessPattern.js
- src/writeFile.js
- tests/index.js
Also it is improve perf, because `webpack` cache `stats` and other stuff (https://github.com/webpack/webpack/blob/efc576c8b744e7a015ab26f1f46932ba3ca7d4f1/lib/node/NodeEnvironmentPlugin.js#L14) using `CachedInputFileSystem`
- Closes https://github.com/webpack-contrib/copy-webpack-plugin/issues/204
> feat: use `compiler.inputFileSystem` instead `fs`

- README.md
fix README examples to be valid
> docs(README): add missing comma in examples

- package.json
- src/preProcessPattern.js
- src/utils/promisify.js
- src/writeFile.js
`pify` seems to not be working correctly when a decorated file system is used as `inputFileSystem`.
Fix #217
> fix: replace `pify` with simpler promise helpers

- README.md
- src/processPattern.js
- src/writeFile.js
- tests/index.js
We want to match some of our existing asset logic which generates image file names from the source paths. Having a function that generates those paths seemed like the simplest solution.
This mirrors the way the `file-loader` works, allowing to reuse logic. https://github.com/webpack-contrib/file-loader#regexp
> feat(processPattern): add support for `{RegExp)` matches (`pattern.test`)

- README.md
Github creates id's for heading but they're lowercase, so `#toType` wont work, instead use `#totype` for example.
> docs(README): correct anchor link (`patterns.toType`)

- README.md
fixes #160
Edit transform documentation to specify that a Promise may be returned.
> docs(README): clarify `{Promise}` usage (`pattern.transform`) (#160)

- README.md
Following the example, webpack emits an error
```sh
TypeError: Path must be a string.
```
Replaced with string, which actually works fine in the latest webpack 4.15.0
> docs(README): Context option is a string, not array

- src/processPattern.js
- tests/index.js
At the moment when using globs with `watch` mode and files are added after the initial compilation, they are not copied because the globbed `dirname` is not added to the context
> fix(processPattern): add `glob` directory context to `contextDependencies`

- src/processPattern.js
- tests/index.js
In some cases we might have someone like this which in that cause we wouldn't want to add the parent directory as a webpack context dependencies
```
{
ignore: [ '.gitkeep', '**/.DS_Store', '**/Thumbs.db' ],
from: { glob: 'favicon.ico', dot: true },
toType: 'dir',
fromType: 'glob'
}
```
> fix(processPattern): don't add `'glob'` as directory when it is a file (`contextDependencies`)

- README.md
- src/writeFile.js
- tests/index.js
updated version of the PR: webpack-contrib/copy-webpack-plugin/pull/115.
Should resolve #107.
> Why another PR?
>
> Since the other PR is not being updated for some time, and needed to be updated for some time, since I did some differences (mostly to allow Promises with transformPath will need a review)
differences:
- added support to Promises to be aligned with transform (since transform supports Promises)
- updated the tests since there are more test files test files
- updated the Readme to include implementation examples (Function & Promise) like transform in the Readme
- rebased with the latest version
> feat: add support for target path transform

- src/preProcessPattern.js
- tests/index.js
In certain cases depending on the inputFileSystem `stats` doesn't throw, but returns a falsey value such as `undefined` and `null`. In this case an error from globby will be thrown `Patterns must be a string or an array of strings`
Relates to: https://github.com/angular/angular-cli/issues/12686
> fix: handle undefined and null as stats value

- README.md
The example for `transformPath`(`Promise`) uses `transform`, fixed that.
> docs(README): fix function name `transformPath` in code sample

- src/preProcessPattern.js
- tests/index.js
> fix(preProcessPattern): throw an `{Error}` if `pattern.from` is empty or `undefined`

- src/preProcessPattern.js
- test/CopyPlugin.test.js
Handle `[contenthash]` as template
No
No
> fix: handle `[contenthash]` as template

- package-lock.json
- package.json
- src/index.js
- test/CopyPlugin.test.js
BREAKING CHANGE: minimum require webpack version is 4
webpack@3 is outdated
Yes
No
> refactor: break compatibility with < webpack 4

- src/preProcessPattern.js
- src/processPattern.js
- test/CopyPlugin.test.js
> fix: handles new files when you in watch mode

- src/processPattern.js
- test/CopyPlugin.test.js
> refactor: use `Error` class for error

- src/postProcessPattern.js
- src/preProcessPattern.js
- test/CopyPlugin.test.js
> fix: copy only modified files when you use patterns with difference to

- test/CopyPlugin.test.js
Tests
We merge this before as fix, before you can use empty pattern (it is mean current context), this behavior is misleading so better avoid this.
No
> test: empty from

- package-lock.json
- package.json
- src/preProcessPattern.js
- test/CopyPlugin.test.js
fixes #345
No, it is change behavior, but previously will be buggy
No
> fix: respect base of `glob` for context dependencies

- README.md
- src/postProcessPattern.js
- src/preProcessPattern.js
- src/processPattern.js
- test/CopyPlugin.test.js
> fix: watch on windows

- package-lock.json
- package.json
- src/postProcessPattern.js
From docs:
> findCacheDir([options])
Finds the cache directory using the supplied options. The algorithm tries to find a package.json file, searching every parent directory of the cwd specified (or implied from other options). It returns a string containing the absolute path to the cache directory, or null if package.json was never found.
No
hard to tests this
> fix: add fallback to transform cache directory

- src/preProcessPattern.js
- src/processPattern.js
- test/CopyPlugin.test.js
Emit errors instead throw, so we don't break compilation if error happens
No
No
> fix: emit errors instead throw

- src/preProcessPattern.js
- src/utils/isTemplateLike.js
- test/CopyPlugin.test.js
template regex changed so we should update fix here too
No
No
> fix: better determinate template in `to` option

- package-lock.json
- package.json
> chore: remove unused deps

- src/postProcessPattern.js
- test/CopyPlugin.test.js
fixes #383 fixes #389 fixes #378
no, if somebody find regression feel free to open issue
no
> fix: use posix separator for emitting assets

- README.md
- test/CopyPlugin.test.js
- test/transformPath-option.test.js
- test/utils/mocks.js
- test/utils/run.js
> refactor: tests

- README.md
> docs: clarify plugin description

- README.md
The markdown generated heading fragments to not contain uppercase letters. It seems Githubs own javascript to handle fragment link clicks knows this and lowercases it on click, the same thing does not happen in webpack.js.org
The PR fixes the problem on webpack.js.org as well
> Fix broken fragment links

- README.md
- src/index.js
- src/options.json
- src/preProcessPattern.js
- test/CopyPlugin.test.js
- test/__snapshots__/validate-options.test.js.snap
- test/validate-options.test.js
validate options
Should be no, of somebody will have problems feel free to open issue
No
> feat: feat validate options

- README.md
- package-lock.json
- package.json
- src/index.js
- src/postProcessPattern.js
- src/processPattern.js
- test/helpers/mocks.js
BREAKING CHANGE: the `logLever` was removed in favor the `infrastructureLogging.level` option, please read the [documentation](https://webpack.js.org/configuration/other-options/#infrastructurelogginglevel)
Migrate on built-in webpack logger
Yes
We will add more tests before release
> feat: migrate on webpack built-in logger

- src/index.js
- src/processPattern.js
- test/CopyPlugin.test.js
Remove old hacks
Yes
BREAKING CHANGE: the `2` version of `webpack-dev-server` is not supported anymore
No
> refactor: remove legacy hacks

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/validate-options.test.js.snap
- test/helpers/run.js
- test/validate-options.test.js
Unify plugin options
Yes
BREAKING CHANGE: the plugin now accepts an object as options, you should change `new CopyPlugin(patterns, options)` to `new CopyPlugin( { patterns, options })`
No
> refactor: plugin options

- README.md
- src/options.json
- src/postProcessPattern.js
- test/__snapshots__/validate-options.test.js.snap
- test/cacheTransform-option.test.js
- test/validate-options.test.js
Rename option to clarify
Yes
BREAKING CHANGE: the `cache` option was renamed to `cacheTransform`
No
> refactor: rename the `cache` option to `cacheTransform`

- README.md
- src/index.js
- src/options.json
- src/preProcessPattern.js
- test/CopyPlugin.test.js
- test/__snapshots__/validate-options.test.js.snap
- test/context-option.test.js
- test/helpers/run.js
- test/validate-options.test.js
No need extra option (less options), you already have `context` option on pattern level
BREAKING CHANGE: the global `context` option was removed in favor the `patten.context` option
No
> refactor: remove the global `context` option

- README.md
edit readmy for toType option
No
No
> chore: edit readmy for toType option

- .gitignore
- src/index.js
- src/postProcessPattern.js
fix compatibility with webpack@5
No
No
> fix: compatibility with webpack@5

- README.md
- src/options.json
- src/processPattern.js
- test/__snapshots__/validate-options.test.js.snap
- test/filter-option.test.js
- test/validate-options.test.js
> feat: added `filter` option

- src/index.js
- src/postProcessPattern.js
- test/CopyPlugin.test.js
> feat: added the `immutable` flag to asset with hash in name

- src/index.js
Now we use webpack filesystem, so you can change it in runtime + now we cache fs calls, should be faster in watch mode
No
No
> feat: use webpack inputFilesystem

- CHANGELOG.md
The syntax change of the ignore option made in #463 wasn’t reflected in the CHANGELOG. Now it has been made clear that there was a change in syntax, and a link to both the old and the new syntax have been added.
> docs: add ignore syntax change to breaking changes in CHANGELOG

- src/index.js
- test/CopyPlugin.test.js
- test/__snapshots__/CopyPlugin.test.js.snap
fix caching in multi compiler mode + refactor
No
No
> refactor: code

- src/index.js
> refactor: handle errors

- package-lock.json
- package.json
- src/index.js
- test/CopyPlugin.test.js
- test/__snapshots__/CopyPlugin.test.js.snap
- test/cacheTransform-option.test.js
fix cache for webpack@4/webpack@5 too + refactor
No
Still WIP
> refactor: fix cache

- src/index.js
fixes #553
No
hard to tests, I will improve this after refactor tests, tested manually
> fix: watching

- src/index.js
- test/__snapshots__/CopyPlugin.test.js.snap
adding files to file dependencies for dir type too
No
No
> fix: watching directories

- README.md
For easy copying of the plugin installation command
> docs: remove "$" from copied console line

- README.md
- package-lock.json
- package.json
- src/index.js
- test/CopyPlugin.test.js
- test/from-option.test.js
- test/globOptions-option.test.js
- test/helpers/BreakContenthashPlugin.js
- test/helpers/run.js
- test/to-option.test.js
- test/toType-option.test.js
- dropped `loader-utils` package
- [template strings in `to` option](https://github.com/webpack/loader-utils#interpolatename) removed in favor [webpack template strings](https://webpack.js.org/configuration/output/#template-strings)
Yes
Migration:
- `[hash]` and `[fullhash]` work as in webpack (i.e. it is hash of build, not hash of file)
- `.[ext]` => `[ext]`
- `[hash]` => `[contenthash]`
- [`<hashType>:contenthash:<digestType>:<length>`] => `[contenthash]` + [`output.hashdigest`](https://webpack.js.org/configuration/output/#outputhashdigest), [`output.hashDigestLength`](https://webpack.js.org/configuration/output/#outputhashdigestlength), [`output.hashFunction`](https://webpack.js.org/configuration/output/#outputhashfunction) options
- [N] - support was limited in …
> refactor: template strings in `to` option

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/validate-options.test.js.snap
- test/priority-option.test.js
- test/validate-options.test.js
> Feat: added `priority` option

- README.md
I was browsing the `filter` documentation as seen [here](https://github.com/webpack-contrib/copy-webpack-plugin#filter) where I noticed that the internal link to `globOptions.ignore` is broken due to a typo.
You can review the fix on my forked repo: https://github.com/mhxbe/copy-webpack-plugin/tree/bugfix/fix-broken-link-globoptions#filter
None.
> Fix broken link to #globoptions

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/transformAll-option.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/transformAll-option.test.js
- test/validate-options.test.js
Added `transformAll` option.
`transformAll` allows to modify the contents of multiple files and save the result to one file.
No
No
> Feat: added transformAll option

- package-lock.json
- src/index.js
Updated "processAssets" hook to use the proper "PROCESS_ASSETS_STAGE_ADDITIONAL" stage instead of "PROCESS_ASSETS_STAGE_ADDITIONS" one.
The `PROCESS_ASSETS_STAGE_ADDITIONAL` assets processing stage is much better suited for this plugin:
> `PROCESS_ASSETS_STAGE_ADDITIONAL` - Add additional assets to the compilation.
I don't think that this could break any public contracts.
Nope.
> fix: process-assets (#600)

- README.md
> Fix unintended cyrillics in README.md

- .github/workflows/nodejs.yml
- .husky/commit-msg
- .husky/pre-commit
- babel.config.js
- package-lock.json
- package.json
- src/index.js
- test/CopyPlugin.test.js
- test/helpers/getCompiler.js
- test/to-option.test.js
- test/toType-option.test.js
`Node.js` v10 dropped
`Node.js` v10 dropped
No
> refactor: Node.js v10 dropped

- src/options.json
- test/__snapshots__/validate-options.test.js.snap
output helpful descriptions and links on errors.
None
No
> fix: output helpful descriptions and links on errors

- package.json
- src/cjs.js
- src/index.js
- src/utils.js
- test/cjs.test.js
- types/cjs.d.ts
- types/index.d.ts
improve types DX
Potentially yes, but we use babel and our code in commonjs format, so we should generate types in the same format
No
> refactor: drop cjs wrapper

- README.md
- src/index.js
- types/index.d.ts
> fix: types

- README.md
> docs(readme): added pnpm and yarn

- src/index.js
- types/index.d.ts
This PR fixes typing errors when trying to return a `Promise<string> | Promise<Buffer>` from `TransformerFunction`, and `TransformAllFunction`,  a `Promise<string>` from `ToFunction` and a `Promise<boolean>` from `Filter`.
All these functions should be possible to return a `Promise` as described in the `README.md`.
By adding the missing types I also found a bug, when using the `ToFunction` and trying to return a `Promise`.
No breaking change.
> fix: add missing promise return types for transform, to and filter functions

- README.md
The previous summary of `context` ("A path that determines how to interpret the from path") was  vague, and didn't really explain what context does.
"*How* does context determine how to interpret the `from` path?" I wondered. It wasn't until looking through the examples, over a day after trying to figure this out, that I had a clue. 
I hope my edit makes the role of `context` clearer, so that others won't have to suffer as I did.
> Clarify what `context` does. Improve phrasing

- babel.config.js
> build: set targets to node 18 in babel.config.js

- README.md
- src/index.js
- test/globOptions-option.test.js
- types/index.d.ts
I started looking at implementing https://github.com/webpack-contrib/copy-webpack-plugin/issues/788 and noticed that some of the glob usage here was more complicated than it needed to be.
The first thing that was being done with the glob results was to check if it's a file. However, globby has an `onlyFiles` option that we can use to avoid the need for that check. After that's done, there's no longer a need to set `objectMode`. Thus, instead of getting back an object, we can simply receive back a string, which is both simpler and better for performance.
n/a
I may follow up with another PR to switch to `tinyglobby`. However, I thought it was better to separate those two refactorings to keep the PRs small and make it easier to debug if there are any unexpected issues
> chore: simplify glob usage
